import { computed, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'

export interface BreadcrumbItem {
  label: string
  to?: string | object
  href?: string
  icon?: string
  active?: boolean
  disabled?: boolean
}

export interface BreadcrumbOptions {
  homeLabel?: string
  homeTo?: string | object
  separator?: string
  maxItems?: number
  showHome?: boolean
  autoGenerate?: boolean
  useRouteName?: boolean
  routeNameMapping?: Record<string, BreadcrumbItem[]>
}

const defaultOptions: BreadcrumbOptions = {
  homeLabel: 'Home',
  homeTo: '/',
  separator: '/',
  maxItems: 5,
  showHome: true,
  autoGenerate: true,
  useRouteName: false,
  routeNameMapping: {},
}

/**
 * Composable untuk manage breadcrumb state dan navigation
 *
 * Features:
 * - Auto-generate breadcrumb dari route
 * - Manual breadcrumb management
 * - Responsive breadcrumb dengan ellipsis
 * - Custom separator dan styling
 * - Navigation handling
 */
export function useBreadcrumb(options: BreadcrumbOptions = {}) {
  const route = useRoute()
  const router = useRouter()

  const config = { ...defaultOptions, ...options }
  const manualItems = ref<BreadcrumbItem[]>([])
  const isManualMode = ref(false)

  // Utility functions
  const formatSegmentLabel = (segment: string): string => {
    return segment
      .split('-')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ')
  }

  // Auto-generate breadcrumb dari route
  const autoGeneratedItems = computed<BreadcrumbItem[]>(() => {
    if (!config.autoGenerate || isManualMode.value)
      return []

    const items: BreadcrumbItem[] = []

    // Add home item jika enabled
    if (config.showHome) {
      items.push({
        label: config.homeLabel!,
        to: config.homeTo,
        active: route.path === config.homeTo,
      })
    }

    // Priority 1: Check route name mapping jika useRouteName enabled
    if (config.useRouteName && route.name && config.routeNameMapping) {
      const mappedItems = config.routeNameMapping[route.name as string]
      if (mappedItems && Array.isArray(mappedItems)) {
        items.push(...mappedItems.map((item, index) => ({
          ...item,
          active: index === mappedItems.length - 1,
        })))
        return items
      }
    }

    // Priority 2: Generate dari route meta breadcrumb
    if (route.meta?.breadcrumb && Array.isArray(route.meta.breadcrumb)) {
      const metaBreadcrumbs = route.meta.breadcrumb as BreadcrumbItem[]
      items.push(...metaBreadcrumbs.map((item, index) => ({
        ...item,
        active: index === metaBreadcrumbs.length - 1,
      })))
    }
    else {
      // Priority 3: Generate dari path segments
      const pathSegments = route.path.split('/').filter(Boolean)
      let currentPath = ''

      pathSegments.forEach((segment, index) => {
        currentPath += `/${segment}`

        // Skip home jika udah ada
        if (config.showHome && currentPath === config.homeTo)
          return

        const isLast = index === pathSegments.length - 1
        const label = formatSegmentLabel(segment)

        items.push({
          label,
          to: isLast ? undefined : currentPath,
          active: isLast,
        })
      })
    }

    return items
  })

  // Final breadcrumb items dengan responsive handling
  const breadcrumbItems = computed<BreadcrumbItem[]>(() => {
    const items = isManualMode.value ? manualItems.value : autoGeneratedItems.value

    // Handle max items dengan ellipsis
    if (config.maxItems && items.length > config.maxItems) {
      const firstItems = items.slice(0, 1)
      const lastItems = items.slice(-(config.maxItems - 2))

      return [
        ...firstItems,
        { label: '...', disabled: true },
        ...lastItems,
      ]
    }

    return items
  })

  // Current page info
  const currentPage = computed(() => {
    const items = breadcrumbItems.value
    return items.find(item => item.active) || items[items.length - 1]
  })

  // Navigation methods
  const navigateTo = (item: BreadcrumbItem | undefined) => {
    if (!item || item.disabled || item.active)
      return

    if (item.href) {
      window.location.href = item.href
    }
    else if (item.to) {
      router.push(item.to)
    }
  }

  const goHome = () => {
    router.push(config.homeTo!)
  }

  const goBack = () => {
    const items = breadcrumbItems.value
    const currentIndex = items.findIndex(item => item.active)

    if (currentIndex > 0) {
      const previousItem = items[currentIndex - 1]
      navigateTo(previousItem)
    }
    else {
      router.back()
    }
  }

  // Manual breadcrumb management
  const setBreadcrumbs = (items: BreadcrumbItem[]) => {
    manualItems.value = items
    isManualMode.value = true
  }

  const addBreadcrumb = (item: BreadcrumbItem, index?: number) => {
    if (!isManualMode.value) {
      manualItems.value = [...autoGeneratedItems.value]
      isManualMode.value = true
    }

    if (typeof index === 'number') {
      manualItems.value.splice(index, 0, item)
    }
    else {
      manualItems.value.push(item)
    }
  }

  const removeBreadcrumb = (index: number) => {
    if (isManualMode.value) {
      manualItems.value.splice(index, 1)
    }
  }

  const clearBreadcrumbs = () => {
    manualItems.value = []
    isManualMode.value = false
  }

  const getBreadcrumbPath = (): string => {
    return breadcrumbItems.value
      .filter(item => !item.disabled)
      .map(item => item.label)
      .join(` ${config.separator} `)
  }

  // Route name mapping management
  const setRouteNameMapping = (routeName: string, items: BreadcrumbItem[]) => {
    if (!config.routeNameMapping) {
      config.routeNameMapping = {}
    }
    config.routeNameMapping[routeName] = items
  }

  const removeRouteNameMapping = (routeName: string) => {
    if (config.routeNameMapping) {
      delete config.routeNameMapping[routeName]
    }
  }

  const enableRouteNameMode = () => {
    config.useRouteName = true
  }

  const disableRouteNameMode = () => {
    config.useRouteName = false
  }

  // Watch route changes untuk auto-update
  watch(
    () => route.path,
    () => {
      if (!isManualMode.value && config.autoGenerate) {
        // Auto-generated items akan update otomatis via computed
      }
    },
    { immediate: true },
  )

  return {
    // State
    breadcrumbItems,
    currentPage,
    isManualMode,
    config,

    // Navigation
    navigateTo,
    goHome,
    goBack,

    // Manual management
    setBreadcrumbs,
    addBreadcrumb,
    removeBreadcrumb,
    clearBreadcrumbs,

    // Route name mapping management
    setRouteNameMapping,
    removeRouteNameMapping,
    enableRouteNameMode,
    disableRouteNameMode,

    // Utilities
    getBreadcrumbPath,
    formatSegmentLabel,
  }
}
